name: Docs

on:
  # release:
  #   types: [created]
  push:
    branches: main

jobs:
  gen-docs:
    name: 'Publish docs / OS ${{ matrix.os }} / Node ${{ matrix.node }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - '18'
    runs-on: '${{ matrix.os }}'
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node }}'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Build Docs
        run: yarn run docs:build

      - name: Build JSON Docs
        run: yarn run docs:json

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: docs
          force_orphan: true
          commit_message: 'docs: update'
