name: Upload Static

on:
  release:
    types: [created]
  # push:
  #   branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build JS Bundler
        run: yarn build
        working-directory: packages/platform-bridge

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_BUCKET_SA_KEY }}'

      - name: Upload to GCP Bucket
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'packages/platform-bridge/dist/bundle/index.js'
          destination: 'static-openfort-xyz/js/${{github.event.release.tag_name}}'
